# Generated by Django 5.0.1 on 2024-01-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
