# Generated by Django 4.2.9 on 2024-01-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
    ]
