# Generated by Django 5.0.1 on 2024-01-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0007_seller_item_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='thriftstore.seller'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
