# Generated by Django 5.0.1 on 2024-01-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0008_alter_item_seller_alter_seller_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thriftstore.seller'),
        ),
    ]
