# Generated by Django 5.0.1 on 2024-01-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0009_alter_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('BOOKS', 'Books'), ('FURNITURE', 'Furniture')], default='CLOTHING', max_length=50),
        ),
    ]
