# Generated by Django 5.0.1 on 2024-01-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0010_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
