# Generated by Django 5.0.1 on 2024-01-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0011_item_shipping_cost_item_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax_rate',
        ),
    ]
