# Generated by Django 5.0.1 on 2024-03-18 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0012_remove_item_shipping_cost_remove_item_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_num',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
