# Generated by Django 5.0.1 on 2024-03-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0014_item_sold_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold_at',
        ),
    ]
