# Generated by Django 5.0.1 on 2024-03-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftstore', '0015_remove_item_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
